import type { Topic } from "./game/types";

export const FALLBACK_TOPICS: Topic[] = [
  { theme: "和食", majorityWord: "寿司", minorityWord: "刺身" },
  { theme: "飲み物", majorityWord: "コーヒー", minorityWord: "紅茶" },
  { theme: "季節", majorityWord: "夏", minorityWord: "梅雨" },
  { theme: "スポーツ", majorityWord: "野球", minorityWord: "ソフトボール" },
  { theme: "乗り物", majorityWord: "電車", minorityWord: "地下鉄" },
  { theme: "ペット", majorityWord: "犬", minorityWord: "猫" },
  { theme: "デザート", majorityWord: "ケーキ", minorityWord: "プリン" },
  { theme: "場所", majorityWord: "海", minorityWord: "プール" },
  { theme: "果物", majorityWord: "りんご", minorityWord: "なし" },
  { theme: "麺類", majorityWord: "ラーメン", minorityWord: "つけ麺" },
  { theme: "イベント", majorityWord: "花火大会", minorityWord: "夏祭り" },
  { theme: "学校", majorityWord: "中学校", minorityWord: "高校" },
  { theme: "家電", majorityWord: "冷蔵庫", minorityWord: "冷凍庫" },
  { theme: "映画", majorityWord: "アクション映画", minorityWord: "アニメ映画" },
  { theme: "天気", majorityWord: "晴れ", minorityWord: "曇り" },
  { theme: "朝食", majorityWord: "パン", minorityWord: "トースト" },
  { theme: "職業", majorityWord: "医者", minorityWord: "看護師" },
  { theme: "旅行", majorityWord: "国内旅行", minorityWord: "海外旅行" },
  { theme: "音楽", majorityWord: "ライブ", minorityWord: "フェス" },
  { theme: "買い物", majorityWord: "コンビニ", minorityWord: "スーパー" },
  { theme: "勉強", majorityWord: "数学", minorityWord: "算数" },
  { theme: "ファッション", majorityWord: "Tシャツ", minorityWord: "ポロシャツ" },
  { theme: "お酒", majorityWord: "ビール", minorityWord: "ハイボール" },
  { theme: "ゲーム", majorityWord: "RPG", minorityWord: "アドベンチャー" },
  { theme: "通信", majorityWord: "電話", minorityWord: "ビデオ通話" },
];
